# Generated by Django 5.0.8 on 2024-08-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Vital Signs",
                "ordering": ["abbreviation"],
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Conditions",
            },
        ),
        migrations.CreateModel(
            name="EvacuationGuidelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.condition"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evacuation Guidelines",
            },
        ),
        migrations.CreateModel(
            name="Prevention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.condition"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Preventions",
            },
        ),
        migrations.CreateModel(
            name="TextEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Text Entries",
            },
        ),
        migrations.CreateModel(
            name="TreatmentPrincipals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.condition"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Treatment Principals",
            },
        ),
        migrations.CreateModel(
            name="VitalSignDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(max_length=100)),
                (
                    "vital_sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.vitalsign"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vital Sign Descriptors",
                "unique_together": {("vital_sign", "descriptor")},
            },
        ),
        migrations.CreateModel(
            name="SignsSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.condition"
                    ),
                ),
                (
                    "related_signs_symptoms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="referenced_by",
                        to="core.signssymptoms",
                    ),
                ),
                (
                    "vital_signs",
                    models.ManyToManyField(blank=True, to="core.vitalsigndescriptor"),
                ),
            ],
            options={
                "verbose_name_plural": "Signs/Symptoms",
            },
        ),
    ]
